// Generated by motif-metal from kinetic-subdivision/chromatic-register, pass 2 of 3 (styles/partition.glsl). Do not edit.
#include <metal_stdlib>
using namespace metal;

// ---- host uniforms (mirrors MotifUniforms.swift; 144 bytes) --------------------------------------------------
struct MotifUniforms {
  float2 res;      // pass resolution in pixels
  float  p;        // loop phase 0..1
  float  L;        // effective loop length in seconds
  float  seed;     // 1..9999
  float  safe;     // 1 = photosensitive-safe limiter
  float  encode;   // 0 = linear premultiplied RGBA, 1 = web-identical final (sRGB, dithered, premultiplied)
  float  _pad;
  float4 bg;       // palette, linear RGB in xyz
  float4 ink;
  float4 a0;
  float4 a1;
  float4 a2;
  float4 media0;   // media input 0: x = attached (0/1), y = video time, zw = pixel size
  float4 media1;
};

// ---- textures: GL samples with v = 0 at the bottom; Metal stores row 0 on top, so v is flipped here ------------
struct MTex { texture2d<float> t; };
constexpr sampler M_smp(coord::normalized, address::clamp_to_edge, filter::linear, mip_filter::linear);
inline float4 M_tex(MTex s, float2 uv) { return s.t.sample(M_smp, float2(uv.x, 1.0 - uv.y)); }
inline float4 M_texLod(MTex s, float2 uv, float lod) { return s.t.sample(M_smp, float2(uv.x, 1.0 - uv.y), level(lod)); }
inline float4 M_texelFetch(MTex s, int2 p, int lod) { return s.t.read(uint2(p.x, int(s.t.get_height(uint(lod))) - 1 - p.y), uint(lod)); }
inline int2 M_texSize(MTex s, int lod) { return int2(int(s.t.get_width(uint(lod))), int(s.t.get_height(uint(lod)))); }

// ---- GLSL maths that Metal lacks or spells differently --------------------------------------------------------
// GLSL lets scalars stand in for vectors in min/max/clamp/mix/step/smoothstep/mod; Metal's overloads do not.
template <typename T> inline T M_min(T a, T b) { return metal::min(a, b); }
template <typename T> inline T M_max(T a, T b) { return metal::max(a, b); }
template <typename T> inline T M_clamp(T x, T lo, T hi) { return metal::clamp(x, lo, hi); }
template <typename T> inline T M_mix(T a, T b, T t) { return metal::mix(a, b, t); }
template <typename T> inline T M_mix(T a, T b, bool t) { return t ? b : a; }
template <typename T> inline T M_step(T e, T x) { return metal::step(e, x); }
template <typename T> inline T M_mod(T x, T y) { return x - y * metal::floor(x / y); }
inline float2 M_min(float2 a, float b) { return metal::min(a, float2(b)); }
inline float2 M_max(float2 a, float b) { return metal::max(a, float2(b)); }
inline float2 M_clamp(float2 x, float lo, float hi) { return metal::clamp(x, float2(lo), float2(hi)); }
inline float2 M_mix(float2 a, float2 b, float t) { return metal::mix(a, b, float2(t)); }
inline float2 M_mix(float2 a, float2 b, bool2 t) { return select(a, b, t); }
inline float2 M_step(float e, float2 x) { return metal::step(float2(e), x); }
inline float2 M_mod(float2 x, float y) { return x - float2(y) * metal::floor(x / float2(y)); }
inline float3 M_min(float3 a, float b) { return metal::min(a, float3(b)); }
inline float3 M_max(float3 a, float b) { return metal::max(a, float3(b)); }
inline float3 M_clamp(float3 x, float lo, float hi) { return metal::clamp(x, float3(lo), float3(hi)); }
inline float3 M_mix(float3 a, float3 b, float t) { return metal::mix(a, b, float3(t)); }
inline float3 M_mix(float3 a, float3 b, bool3 t) { return select(a, b, t); }
inline float3 M_step(float e, float3 x) { return metal::step(float3(e), x); }
inline float3 M_mod(float3 x, float y) { return x - float3(y) * metal::floor(x / float3(y)); }
inline float4 M_min(float4 a, float b) { return metal::min(a, float4(b)); }
inline float4 M_max(float4 a, float b) { return metal::max(a, float4(b)); }
inline float4 M_clamp(float4 x, float lo, float hi) { return metal::clamp(x, float4(lo), float4(hi)); }
inline float4 M_mix(float4 a, float4 b, float t) { return metal::mix(a, b, float4(t)); }
inline float4 M_mix(float4 a, float4 b, bool4 t) { return select(a, b, t); }
inline float4 M_step(float e, float4 x) { return metal::step(float4(e), x); }
inline float4 M_mod(float4 x, float y) { return x - float4(y) * metal::floor(x / float4(y)); }
inline int2 M_min(int2 a, int b) { return metal::min(a, int2(b)); }
inline int2 M_max(int2 a, int b) { return metal::max(a, int2(b)); }
inline int2 M_clamp(int2 x, int lo, int hi) { return metal::clamp(x, int2(lo), int2(hi)); }
inline int3 M_min(int3 a, int b) { return metal::min(a, int3(b)); }
inline int3 M_max(int3 a, int b) { return metal::max(a, int3(b)); }
inline int3 M_clamp(int3 x, int lo, int hi) { return metal::clamp(x, int3(lo), int3(hi)); }
inline int4 M_min(int4 a, int b) { return metal::min(a, int4(b)); }
inline int4 M_max(int4 a, int b) { return metal::max(a, int4(b)); }
inline int4 M_clamp(int4 x, int lo, int hi) { return metal::clamp(x, int4(lo), int4(hi)); }
inline uint2 M_min(uint2 a, uint b) { return metal::min(a, uint2(b)); }
inline uint2 M_max(uint2 a, uint b) { return metal::max(a, uint2(b)); }
inline uint2 M_clamp(uint2 x, uint lo, uint hi) { return metal::clamp(x, uint2(lo), uint2(hi)); }
inline uint3 M_min(uint3 a, uint b) { return metal::min(a, uint3(b)); }
inline uint3 M_max(uint3 a, uint b) { return metal::max(a, uint3(b)); }
inline uint3 M_clamp(uint3 x, uint lo, uint hi) { return metal::clamp(x, uint3(lo), uint3(hi)); }
inline uint4 M_min(uint4 a, uint b) { return metal::min(a, uint4(b)); }
inline uint4 M_max(uint4 a, uint b) { return metal::max(a, uint4(b)); }
inline uint4 M_clamp(uint4 x, uint lo, uint hi) { return metal::clamp(x, uint4(lo), uint4(hi)); }
template <typename T> inline T M_smoothstep(T a, T b, T x) { T t = metal::clamp((x - a) / (b - a), T(0), T(1)); return t * t * (T(3) - T(2) * t); }
inline float2 M_smoothstep(float a, float b, float2 x) { return M_smoothstep(float2(a), float2(b), x); }
inline float3 M_smoothstep(float a, float b, float3 x) { return M_smoothstep(float3(a), float3(b), x); }
inline float4 M_smoothstep(float a, float b, float4 x) { return M_smoothstep(float4(a), float4(b), x); }

template <typename T> inline T M_radians(T d) { return d * 0.017453292519943295; }
template <typename T> inline T M_degrees(T r) { return r * 57.29577951308232; }
template <typename A, typename B> inline auto M_lessThan(A a, B b) { return a < b; }
template <typename A, typename B> inline auto M_lessThanEqual(A a, B b) { return a <= b; }
template <typename A, typename B> inline auto M_greaterThan(A a, B b) { return a > b; }
template <typename A, typename B> inline auto M_greaterThanEqual(A a, B b) { return a >= b; }
template <typename A, typename B> inline auto M_equal(A a, B b) { return a == b; }
template <typename A, typename B> inline auto M_notEqual(A a, B b) { return a != b; }
// GLSL's == and != on vectors give one bool; Metal's give a bool vector.
inline bool M_all(bool x) { return x; }
inline bool M_all(bool2 x) { return all(x); }
inline bool M_all(bool3 x) { return all(x); }
inline bool M_all(bool4 x) { return all(x); }
inline bool M_any(bool x) { return x; }
inline bool M_any(bool2 x) { return any(x); }
inline bool M_any(bool3 x) { return any(x); }
inline bool M_any(bool4 x) { return any(x); }
template <typename A, typename B> inline bool M_eq(A a, B b) { return M_all(a == b); }
template <typename A, typename B> inline bool M_ne(A a, B b) { return M_any(a != b); }
inline float2x2 M_matrixCompMult(float2x2 a, float2x2 b) { return float2x2(a[0] * b[0], a[1] * b[1]); }
inline float3x3 M_matrixCompMult(float3x3 a, float3x3 b) { return float3x3(a[0] * b[0], a[1] * b[1], a[2] * b[2]); }
inline float4x4 M_matrixCompMult(float4x4 a, float4x4 b) { return float4x4(a[0] * b[0], a[1] * b[1], a[2] * b[2], a[3] * b[3]); }
inline float2x2 M_inverse(float2x2 m) { float d = m[0][0] * m[1][1] - m[1][0] * m[0][1]; return float2x2(float2(m[1][1], -m[0][1]), float2(-m[1][0], m[0][0])) * (1.0 / d); }
inline float3x3 M_inverse(float3x3 m) {
  float3 a = m[0], b = m[1], c = m[2];
  float3 r0 = cross(b, c), r1 = cross(c, a), r2 = cross(a, b);
  float inv = 1.0 / dot(r2, c);
  return float3x3(float3(r0.x, r1.x, r2.x), float3(r0.y, r1.y, r2.y), float3(r0.z, r1.z, r2.z)) * inv;
}
// GL's window y points up and the entry point flips Metal's (fc.y = height - pos.y), so dFdy changes sign.
template <typename T> inline T M_dFdy(T v) { return -dfdy(v); }
inline uint   floatBitsToUint(float x)  { return as_type<uint>(x); }
inline uint2  floatBitsToUint(float2 x) { return as_type<uint2>(x); }
inline uint3  floatBitsToUint(float3 x) { return as_type<uint3>(x); }
inline uint4  floatBitsToUint(float4 x) { return as_type<uint4>(x); }
inline int    floatBitsToInt(float x)   { return as_type<int>(x); }
inline int2   floatBitsToInt(float2 x)  { return as_type<int2>(x); }
inline int3   floatBitsToInt(float3 x)  { return as_type<int3>(x); }
inline int4   floatBitsToInt(float4 x)  { return as_type<int4>(x); }
inline float  uintBitsToFloat(uint x)   { return as_type<float>(x); }
inline float2 uintBitsToFloat(uint2 x)  { return as_type<float2>(x); }
inline float3 uintBitsToFloat(uint3 x)  { return as_type<float3>(x); }
inline float4 uintBitsToFloat(uint4 x)  { return as_type<float4>(x); }
inline float  intBitsToFloat(int x)     { return as_type<float>(x); }

// ---- hoisted: macros, structs, program-scope constants ---------------------------------------------------------
#define TAU 6.283185307179586
#define PI 3.141592653589793
#define M_PH (u_p * TAU)
#define SPLIT_DIRECTION_AUTO 0
#define SPLIT_DIRECTION_HORIZONTAL 1
#define SPLIT_DIRECTION_VERTICAL 2
#define SPLIT_DIRECTION_ALTERNATING 3
#define CELL_SCALE_ANCHORS 0
#define CELL_SCALE_BALANCED 1
#define CELL_SCALE_FRAGMENTS 2
#define MOTION_CHARACTER_GLIDE 0
#define MOTION_CHARACTER_SPRING 1
#define MOTION_CHARACTER_STEPS 2
#define MOTION_CHARACTER_SHUTTER 3
#define SOURCE_SAMPLING_INTACT 0
#define SOURCE_SAMPLING_STRETCH 1
#define SOURCE_SAMPLING_SCANLINE 2
#define SOURCE_SAMPLING_MIRROR 3
#define EDGE_LANGUAGE_HAIRLINE 0
#define EDGE_LANGUAGE_GUTTER 1
#define EDGE_LANGUAGE_DOUBLE 2
#define EDGE_LANGUAGE_TICKS 3
#define EDGE_LANGUAGE_NONE 4
#define DISPLACEMENT_AXIS_BOTH 0
#define DISPLACEMENT_AXIS_HORIZONTAL 1
#define DISPLACEMENT_AXIS_VERTICAL 2
#define DISPLACEMENT_AXIS_RADIAL 3

// ---- pass: every function is a member so uniforms read as plain identifiers --------------------------------------
struct MPass_kinetic_subdivision_chromatic_register_p1 {
float2 u_res;
float u_p;
float u_L;
float u_seed;
float u_safe;
float3 u_bg, u_ink, u_a0, u_a1, u_a2;
MTex u_buf0, u_buf1, u_buf2, u_buf3;
uint M_pcg(uint v) { uint s = v * 747796405u + 2891336453u; uint w = ((s >> ((s >> 28u) + 4u)) ^ s) * 277803737u; return (w >> 22u) ^ w; }
uint M_seedU() { return M_pcg(uint(u_seed) * 2654435761u); }
float M_u2f(uint x) { return float(x >> 8u) * (1.0 / 16777216.0); }
float h11(float x) { return M_u2f(M_pcg(floatBitsToUint(x + 0.0) ^ M_seedU())); }
float h21(float2 p) { return M_u2f(M_pcg(M_pcg(floatBitsToUint(p.x + 0.0) ^ M_seedU()) ^ floatBitsToUint(p.y + 0.0))); }
float2 h22(float2 p) { uint a = M_pcg(M_pcg(floatBitsToUint(p.x + 0.0) ^ M_seedU()) ^ floatBitsToUint(p.y + 0.0)); return float2(M_u2f(a), M_u2f(M_pcg(a))); }
float3 h33(float3 p) { uint a = M_pcg(M_pcg(M_pcg(floatBitsToUint(p.x + 0.0) ^ M_seedU()) ^ floatBitsToUint(p.y + 0.0)) ^ floatBitsToUint(p.z + 0.0)); uint b = M_pcg(a); return float3(M_u2f(a), M_u2f(b), M_u2f(M_pcg(b))); }
float2 M_seedOff() { return float2(M_u2f(M_seedU()), M_u2f(M_pcg(M_seedU()))) * 173.0 - 86.0; }
float2x2 rot(float a) { float c = cos(a), s = sin(a); return float2x2(float2(c, s),float2( -s, c)); }
float sat(float x) { return M_clamp(x, 0.0, 1.0); }
float3 sat(float3 x) { return M_clamp(x, 0.0, 1.0); }
float remap(float x, float a, float b) { return sat((x - a) / (b - a)); }
float smin(float a, float b, float k) { float h = sat(0.5 + 0.5 * (b - a) / k); return M_mix(b, a, h) - k * h * (1.0 - h); }
float smax(float a, float b, float k) { return -smin(-a, -b, k); }
float luma(float3 c) { return dot(c, float3(0.2126, 0.7152, 0.0722)); }
float2 lc(float k, float ph) { float a = TAU * (k * u_p + ph); return float2(cos(a), sin(a)); }
float lsin(float k, float ph) { return sin(TAU * (k * u_p + ph)); }
float lsaw(float k, float ph) { return fract(k * u_p + ph); }
float4 M_mod289(float4 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
float3 M_mod289(float3 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
float M_mod289(float x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }
float4 M_perm(float4 x) { return M_mod289(((x * 34.0) + 1.0) * x); }
float M_perm(float x) { return M_mod289(((x * 34.0) + 1.0) * x); }
float4 M_tis(float4 r) { return 1.79284291400159 - 0.85373472095314 * r; }
float M_tis(float r) { return 1.79284291400159 - 0.85373472095314 * r; }
float snoise(float3 v) {
  const float2 C = float2(1.0 / 6.0, 1.0 / 3.0); const float4 D = float4(0.0, 0.5, 1.0, 2.0);
  float3 i = floor(v + dot(v, C.yyy)); float3 x0 = v - i + dot(i, C.xxx);
  float3 g = M_step(x0.yzx, x0.xyz); float3 l = 1.0 - g; float3 i1 = M_min(g.xyz, l.zxy); float3 i2 = M_max(g.xyz, l.zxy);
  float3 x1 = x0 - i1 + C.xxx; float3 x2 = x0 - i2 + C.yyy; float3 x3 = x0 - D.yyy;
  i = M_mod289(i);
  float4 p = M_perm(M_perm(M_perm(i.z + float4(0.0, i1.z, i2.z, 1.0)) + i.y + float4(0.0, i1.y, i2.y, 1.0)) + i.x + float4(0.0, i1.x, i2.x, 1.0));
  float n_ = 0.142857142857; float3 ns = n_ * D.wyz - D.xzx;
  float4 j = p - 49.0 * floor(p * ns.z * ns.z); float4 x_ = floor(j * ns.z); float4 y_ = floor(j - 7.0 * x_);
  float4 x = x_ * ns.x + ns.yyyy; float4 y = y_ * ns.x + ns.yyyy; float4 h = 1.0 - abs(x) - abs(y);
  float4 b0 = float4(x.xy, y.xy); float4 b1 = float4(x.zw, y.zw);
  float4 s0 = floor(b0) * 2.0 + 1.0; float4 s1 = floor(b1) * 2.0 + 1.0; float4 sh = -M_step(h, float4(0.0));
  float4 a0 = b0.xzyw + s0.xzyw * sh.xxyy; float4 a1 = b1.xzyw + s1.xzyw * sh.zzww;
  float3 p0 = float3(a0.xy, h.x); float3 p1 = float3(a0.zw, h.y); float3 p2 = float3(a1.xy, h.z); float3 p3 = float3(a1.zw, h.w);
  float4 norm = M_tis(float4(dot(p0, p0), dot(p1, p1), dot(p2, p2), dot(p3, p3)));
  p0 *= norm.x; p1 *= norm.y; p2 *= norm.z; p3 *= norm.w;
  float4 m = M_max(0.6 - float4(dot(x0, x0), dot(x1, x1), dot(x2, x2), dot(x3, x3)), 0.0); m = m * m;
  return 42.0 * dot(m * m, float4(dot(p0, x0), dot(p1, x1), dot(p2, x2), dot(p3, x3)));
}
float4 M_grad4(float j, float4 ip) {
  const float4 ones = float4(1.0, 1.0, 1.0, -1.0); float4 p, s;
  p.xyz = floor(fract(float3(j) * ip.xyz) * 7.0) * ip.z - 1.0; p.w = 1.5 - dot(abs(p.xyz), ones.xyz);
  s = float4(M_lessThan(p, float4(0.0))); p.xyz = p.xyz + (s.xyz * 2.0 - 1.0) * s.www; return p;
}
float snoise(float4 v) {
  const float4 C = float4(0.138196601125011, 0.276393202250021, 0.414589803375032, -0.447213595499958);
  float4 i = floor(v + dot(v, float4(0.309016994374947451))); float4 x0 = v - i + dot(i, C.xxxx);
  float4 i0; float3 isX = M_step(x0.yzw, x0.xxx); float3 isYZ = M_step(x0.zww, x0.yyz);
  i0.x = isX.x + isX.y + isX.z; i0.yzw = 1.0 - isX; i0.y += isYZ.x + isYZ.y; i0.zw += 1.0 - isYZ.xy; i0.z += isYZ.z; i0.w += 1.0 - isYZ.z;
  float4 i3 = M_clamp(i0, 0.0, 1.0); float4 i2 = M_clamp(i0 - 1.0, 0.0, 1.0); float4 i1 = M_clamp(i0 - 2.0, 0.0, 1.0);
  float4 x1 = x0 - i1 + C.xxxx; float4 x2 = x0 - i2 + C.yyyy; float4 x3 = x0 - i3 + C.zzzz; float4 x4 = x0 + C.wwww;
  i = M_mod289(i);
  float j0 = M_perm(M_perm(M_perm(M_perm(i.w) + i.z) + i.y) + i.x);
  float4 j1 = M_perm(M_perm(M_perm(M_perm(i.w + float4(i1.w, i2.w, i3.w, 1.0)) + i.z + float4(i1.z, i2.z, i3.z, 1.0)) + i.y + float4(i1.y, i2.y, i3.y, 1.0)) + i.x + float4(i1.x, i2.x, i3.x, 1.0));
  float4 ip = float4(1.0 / 294.0, 1.0 / 49.0, 1.0 / 7.0, 0.0);
  float4 p0 = M_grad4(j0, ip); float4 p1 = M_grad4(j1.x, ip); float4 p2 = M_grad4(j1.y, ip); float4 p3 = M_grad4(j1.z, ip); float4 p4 = M_grad4(j1.w, ip);
  float4 norm = M_tis(float4(dot(p0, p0), dot(p1, p1), dot(p2, p2), dot(p3, p3)));
  p0 *= norm.x; p1 *= norm.y; p2 *= norm.z; p3 *= norm.w; p4 *= M_tis(dot(p4, p4));
  float3 m0 = M_max(0.6 - float3(dot(x0, x0), dot(x1, x1), dot(x2, x2)), 0.0); float2 m1 = M_max(0.6 - float2(dot(x3, x3), dot(x4, x4)), 0.0);
  m0 = m0 * m0; m1 = m1 * m1;
  return 49.0 * (dot(m0 * m0, float3(dot(p0, x0), dot(p1, x1), dot(p2, x2))) + dot(m1 * m1, float2(dot(p3, x3), dot(p4, x4))));
}
float ln2(float2 x, float k, float r) { return snoise(float4(x + M_seedOff(), r * lc(k, 0.0))); }
float ln3(float3 x, float k, float r) { float2 c = r * lc(k, 0.0); return snoise(float4(x.xy + M_seedOff(), x.z + c.x, c.y)); }
float lfbm(float2 x, int oct, float k, float r) {
  float s = 0.0, a = 0.5; float2x2 m = float2x2(float2(1.6, 1.2),float2( -1.2, 1.6));
  for (int i = 0; i < 8; i++) { if (i >= oct) break; s += a * ln2(x, k, r); x = m * x + 11.7; a *= 0.5; }
  return s;
}
float lfbm3(float3 x, int oct, float k, float r) {
  float s = 0.0, a = 0.5;
  for (int i = 0; i < 8; i++) { if (i >= oct) break; s += a * ln3(x, k, r); x = x * 2.02 + float3(7.1, 3.3, 1.9); a *= 0.5; }
  return s;
}
float lridge(float2 x, int oct, float k, float r) {
  float s = 0.0, a = 0.5; float2x2 m = float2x2(float2(1.6, 1.2),float2( -1.2, 1.6));
  for (int i = 0; i < 8; i++) { if (i >= oct) break; float n = 1.0 - abs(ln2(x, k, r)); s += a * n * n; x = m * x + 5.3; a *= 0.5; }
  return s;
}
float3 lvoro(float2 x, float jit, float k, float amp) {
  float2 n = floor(x), f = fract(x); float d1 = 8.0, d2 = 8.0, id = 0.0;
  for (int j = -1; j <= 1; j++) for (int i = -1; i <= 1; i++) {
    float2 g = float2(float(i), float(j)); float2 h = h22(n + g);
    float2 o = 0.5 + jit * (h - 0.5) + amp * lc(k, h.x) * 0.5 * (0.5 + h.y);
    float d = length(g + o - f);
    if (d < d1) { d2 = d1; d1 = d; id = h.x; } else if (d < d2) d2 = d;
  }
  return float3(d1, d2, id);
}
float sdSeg(float2 p, float2 a, float2 b) { float2 pa = p - a, ba = b - a; float h = sat(dot(pa, ba) / dot(ba, ba)); return length(pa - ba * h); }
float sdBox(float2 p, float2 b) { float2 d = abs(p) - b; return length(M_max(d, 0.0)) + M_min(M_max(d.x, d.y), 0.0); }
float sdBox3(float3 p, float3 b) { float3 q = abs(p) - b; return length(M_max(q, 0.0)) + M_min(M_max(q.x, M_max(q.y, q.z)), 0.0); }
float sdTorus(float3 p, float2 t) { float2 q = float2(length(p.xz) - t.x, p.y); return length(q) - t.y; }
float glowd(float d, float w) { return w / (abs(d) + w); }
float glow2(float d, float w) { float x = d / w; return 1.0 / (1.0 + x * x); }
float gauss1(float d, float w) { return exp(-d * d / (w * w)); }
float line(float d, float w) { return 1.0 - M_smoothstep(w * 0.5, w * 0.5 + 1.5 / M_min(u_res.x, u_res.y), d); }
float aa() { return 1.5 / M_min(u_res.x, u_res.y); }
float3 ramp(float t) { 
  t = sat(t) * 4.0;
  if (t < 1.0) return M_mix(u_bg, u_a2, t);
  if (t < 2.0) return M_mix(u_a2, u_a0, t - 1.0);
  if (t < 3.0) return M_mix(u_a0, u_a1, t - 2.0);
  return M_mix(u_a1, u_ink, t - 3.0);
}
float3 accent(float i) { float j = M_mod(floor(i), 3.0); return j < 0.5 ? u_a0 : j < 1.5 ? u_a1 : u_a2; }
float3 hot(float t) { t = M_max(t, 0.0); return M_mix(u_a2, u_a0, sat(t * 1.4)) * sat(t * 3.0) + u_ink * M_max(t - 0.6, 0.0) * 1.2 + u_a1 * sat(t - 1.0) * 0.5; }
float3 aces(float3 x) { return sat((x * (2.51 * x + 0.03)) / (x * (2.43 * x + 0.59) + 0.14)); }
float3 bb(float T) { 
  T = M_clamp(T, 1000.0, 40000.0) / 100.0; float3 c;
  c.r = T <= 66.0 ? 1.0 : sat(1.2929 * pow(T - 60.0, -0.1332));
  c.g = T <= 66.0 ? sat(0.3901 * log(T) - 0.6318) : sat(1.1298 * pow(T - 60.0, -0.0755));
  c.b = T >= 66.0 ? 1.0 : (T <= 19.0 ? 0.0 : sat(0.5432 * log(T - 10.0) - 1.1963));
  return c * c;
}
float4 emit(float3 c) { c = M_max(c, 0.0); return float4(c, M_max(c.r, M_max(c.g, c.b))); }
float4 solid(float3 c, float a) { return float4(c * a, a); }
float4 over(float4 top, float4 base) { return top + base * (1.0 - top.a); }
float4 addc(float4 a, float4 b) { return float4(a.rgb + b.rgb, M_max(a.a, b.a)); }
float M_rate(float n) { n = M_max(0.0, floor(n + 0.5)); return u_safe > 0.5 ? M_min(n, floor(3.0 * u_L)) : n; }
float tslot(float n) { float r = M_rate(n); return r < 1.0 ? 0.0 : floor(fract(u_p) * r); }
float tfrac(float n) { float r = M_rate(n); return r < 1.0 ? 0.0 : fract(fract(u_p) * r); }
float safeCycles(float k) { return M_rate(k); }
float strobe(float k, float duty) { float r = M_rate(k); if (r < 1.0) return duty; float f = fract(u_p * r); float soft = u_safe > 0.5 ? 0.18 : 0.02; return M_smoothstep(0.0, soft, f) * (1.0 - M_smoothstep(duty, duty + soft, f)); }
float flashAmt(float x) { return u_safe > 0.5 ? x * 0.35 : x; }
float pulse(float s, float k, float ph, float wd) { float x = fract(s - k * u_p - ph); return exp(-x * x / (wd * wd)) + exp(-(1.0 - x) * (1.0 - x) / (wd * wd)); }
float growEnv(float h) { float x = fract(u_p); float a = (1.0 - h) * 0.5; return M_smoothstep(0.0, a, x) * (1.0 - M_smoothstep(1.0 - a * 0.6, 1.0, x)); }
float2 M_uv(float2 fc) { return (fc - 0.5 * u_res) / M_min(u_res.x, u_res.y); }
float2 M_asp() { return u_res / M_min(u_res.x, u_res.y); }
float4 buf(MTex b, float2 fc) { return M_tex(b, fc / u_res); }
int p_variant;
int p_depth;
int p_rate;
float p_smoothness;
float p_amount;
float p_edge;
float p_smear;
float p_ink;
float p_imageMix;
int p_topologyHold;
int p_splitDirection;
int p_cellScale;
int p_motionCharacter;
int p_sourceSampling;
int p_edgeLanguage;
float p_focalProtection;
float p_splitBias;
int p_displacementAxis;
float p_focalPointX;
float p_focalPointY;
float p_edgeTintR;
float p_edgeTintG;
float p_edgeTintB;
float p_echoLength;
float p_colorSeparation;
float2 v_focalPoint() { return float2(p_focalPointX, p_focalPointY); }
float3 s_edgeTint() { return float3(p_edgeTintR, p_edgeTintG, p_edgeTintB); }
float3 c_edgeTint() { float3 c = s_edgeTint(); return M_mix(c / 12.92, pow((c + 0.055) / 1.055, float3(2.4)), M_step(float3(0.04045), c)); }
MTex u_source;
float u_sourceOn;
float2 u_sourceSize;
float u_sourceTime;
float4 m_source(float2 q) { return M_tex(u_source, M_clamp(q, float2(0.0), float2(1.0))); }
float4 m_sourcePx(float2 fc) { return m_source(fc / u_res); }
float4 m_sourceUV(float2 uv) { return m_source(uv * M_min(u_res.x, u_res.y) / u_res + 0.5); }
float4 K_source(float2 q) {
 q=M_clamp(q,float2(0.0),float2(1.0));
 float4 fallback=M_tex(u_buf0,q);
 float4 media=m_source(q);
 float3 opaqueMedia=media.rgb+u_bg*(1.0-media.a);
 return float4(M_mix(fallback.rgb,opaqueMedia,u_sourceOn*p_imageMix),1.0);
}
float K_edge(float d, float w) {return 1.0-M_smoothstep(w*0.35,w*1.6,d);}
float4 motif(float2 uv, float2 fc) {
 float2 q=fc/u_res,lo=float2(0.0),hi=float2(1.0);
 float id=u_seed+1.0,dist=1e5;
 float rate=safeCycles(float(p_rate));
 float ph=rate<1.0?0.0:fract(u_p)*rate;
 float slot=floor(ph),nextSlot=rate<1.0?0.0:M_mod(slot+1.0,rate);
 float fraction=fract(ph);
 float t=p_smoothness<0.001?0.0:sat(fraction/M_max(0.001,p_smoothness));
 t=t*t*(3.0-2.0*t);
 if(p_motionCharacter==1)t=M_clamp(1.0+2.7*pow(t-1.0,3.0)+1.7*pow(t-1.0,2.0),-0.12,1.12);
 else if(p_motionCharacter==2)t=floor(t*5.0)/5.0;
 else if(p_motionCharacter==3)t=M_step(0.82,t);
 float hold=float(p_topologyHold);
 float epoch=hold<1.0?0.0:floor(ph/hold);
 float epochs=hold<1.0?1.0:ceil(rate/hold);
 float nextEpoch=hold<1.0?0.0:M_mod(epoch+1.0,epochs);
 float span=hold<1.0?1.0:M_min(hold,rate-epoch*hold);
 float local=hold<1.0?0.0:ph-epoch*hold;
 float geomT=hold<1.0?0.0:M_smoothstep(M_max(0.0,span-0.7),span,local);
 int levels=p_cellScale==0?M_max(2,p_depth-1):(p_cellScale==2?M_min(7,p_depth+1):p_depth);
 for(int i=0;i<7;i++){
   if(i>=levels)break;
   float level=float(i),base=id*1.13+level*17.0;
   bool vertical=h11(id*2.17+level*31.0)>0.42;
   if(p_variant==2)vertical=true;
   else if(p_variant==3||p_variant==7)vertical=false;
   else if(p_variant==1)vertical=M_mod(level,3.0)!=1.0;
   if(p_splitDirection==1)vertical=false;
   else if(p_splitDirection==2)vertical=true;
   else if(p_splitDirection==3)vertical=M_mod(level,2.0)<1.0;
   float a=h21(float2(base,epoch)),b=h21(float2(base,nextEpoch));
   float ratio=M_clamp(0.5+(M_mix(a,b,geomT)-0.5)*0.48+p_splitBias*0.35,0.12,0.88);
   if(vertical){float x=M_mix(lo.x,hi.x,ratio);dist=M_min(dist,abs(q.x-x)*u_res.x);if(q.x<x){hi.x=x;id=id*2.31+1.0;}else{lo.x=x;id=id*2.31+2.0;}}
   else{float y=M_mix(lo.y,hi.y,ratio);dist=M_min(dist,abs(q.y-y)*u_res.y);if(q.y<y){hi.y=y;id=id*2.71+1.0;}else{lo.y=y;id=id*2.71+2.0;}}
 }
 dist=M_min(dist,M_min(M_min((q.x-lo.x)*u_res.x,(hi.x-q.x)*u_res.x),M_min((q.y-lo.y)*u_res.y,(hi.y-q.y)*u_res.y)));
 float2 va=h22(float2(id*5.31,slot)),vb=h22(float2(id*5.31,nextSlot));
 float2 off=(M_mix(va,vb,t)-0.5)*2.0;
 return float4(h11(id*1.47),sat(dist/12.0),off*0.5+0.5);
}
float4 gl_FragCoord;
float M_dither(float2 fc) { return M_u2f(M_pcg(uint(fc.x) * 1973u ^ M_pcg(uint(fc.y) * 9277u))) - 0.5; }
float3 M_srgb(float3 c) { return M_mix(c * 12.92, 1.055 * pow(c, float3(1.0 / 2.4)) - 0.055, M_step(0.0031308, c)); }
  MPass_kinetic_subdivision_chromatic_register_p1(MTex b0, MTex b1, MTex b2, MTex b3, MTex i0) : u_buf0(b0), u_buf1(b1), u_buf2(b2), u_buf3(b3), u_source(i0) {}
};

// ---- entry point: pass 1 ----------------------------------------------------------------------------
fragment float4 mfs_kinetic_subdivision_chromatic_register_p1(float4 pos [[position]],
    constant MotifUniforms& U [[buffer(0)]],
    constant float* P [[buffer(1)]],
    texture2d<float> buf0 [[texture(0)]], texture2d<float> buf1 [[texture(1)]],
    texture2d<float> buf2 [[texture(2)]], texture2d<float> buf3 [[texture(3)]], texture2d<float> in0 [[texture(4)]])
{
  MPass_kinetic_subdivision_chromatic_register_p1 M(MTex{buf0}, MTex{buf1}, MTex{buf2}, MTex{buf3}, MTex{in0});
  M.u_res = U.res; M.u_p = U.p; M.u_L = U.L; M.u_seed = U.seed; M.u_safe = U.safe;
  M.u_bg = U.bg.xyz; M.u_ink = U.ink.xyz; M.u_a0 = U.a0.xyz; M.u_a1 = U.a1.xyz; M.u_a2 = U.a2.xyz;
  M.u_sourceOn = U.media0.x;
  M.u_sourceTime = U.media0.y;
  M.u_sourceSize = U.media0.zw;
  M.p_variant = int(rint(P[0]));
  M.p_depth = int(rint(P[1]));
  M.p_rate = int(rint(P[2]));
  M.p_smoothness = P[3];
  M.p_amount = P[4];
  M.p_edge = P[5];
  M.p_smear = P[6];
  M.p_ink = P[7];
  M.p_imageMix = P[8];
  M.p_topologyHold = int(rint(P[9]));
  M.p_splitDirection = int(rint(P[10]));
  M.p_cellScale = int(rint(P[11]));
  M.p_motionCharacter = int(rint(P[12]));
  M.p_sourceSampling = int(rint(P[13]));
  M.p_edgeLanguage = int(rint(P[14]));
  M.p_focalProtection = P[15];
  M.p_splitBias = P[16];
  M.p_displacementAxis = int(rint(P[17]));
  M.p_focalPointX = P[18];
  M.p_focalPointY = P[19];
  M.p_edgeTintR = P[20];
  M.p_edgeTintG = P[21];
  M.p_edgeTintB = P[22];
  M.p_echoLength = P[23];
  M.p_colorSeparation = P[24];
  float2 fc = float2(pos.x, U.res.y - pos.y);     // GL convention: origin bottom-left
  M.gl_FragCoord = float4(fc, pos.z, pos.w);
  float4 c = M.motif(M.M_uv(fc), fc);
  if (any(isnan(c))) c = float4(0.0);
  if (U.encode < 0.5) return c;
  c = max(c, float4(0.0));
  float a = clamp(max(c.a, max(c.r, max(c.g, c.b))), 0.0, 1.0);
  float3 s = a > 1e-5 ? M_clamp(c.rgb / a, 0.0, 1.0) : float3(0.0);
  s = M.M_srgb(s) + M.M_dither(fc) / 255.0;
  return float4(M_clamp(s, 0.0, 1.0) * a, a);
}
