/* Independent pitch and transport speed using bounded, four-grain overlap/add. */
class JourneyPlayer extends AudioWorkletProcessor {
 static get parameterDescriptors(){return[{name:'speed',defaultValue:1,minValue:.35,maxValue:2.8,automationRate:'k-rate'},{name:'pitch',defaultValue:1,minValue:.5,maxValue:2,automationRate:'k-rate'}]}
 constructor(){super();this.left=null;this.right=null;this.sr=24000;this.head=0;this.length=0;this.loopStart=0;this.span=0;this.nativeBpm=72;this.pendingSync=null;this.correction=0;this.grainSize=Math.round(sampleRate*.085);this.hop=Math.round(this.grainSize/4);this.counter=0;this.startAt=0;this.env=0;this.envT=1;this.slew=1/(sampleRate*.008);this.resetMsg=null;this.xf=0;this.xfN=Math.round(sampleRate*.012);this.xfPos=0;this.prevDirect=false;this.grains=Array.from({length:4},()=>({age:this.grainSize,pos:0}));this.window=new Float32Array(this.grainSize);for(let i=0;i<this.grainSize;i++)this.window[i]=.5-.5*Math.cos(2*Math.PI*i/this.grainSize);this.port.onmessage=e=>{const d=e.data;if(d.type==='load'){this.left=d.left;this.right=d.right||d.left;this.length=d.left.length;this.sr=d.sampleRate;this.configureLoop(d.offset||0,d.bpm||72);this.reset(0);this.env=0;this.envT=1;this.resetMsg=null;this.port.postMessage({type:'ready'})}else if(d.type==='reset'){this.resetMsg=d;this.envT=0}else if(d.type==='sync'){this.pendingSync=d;}else if(d.type==='clear'){this.left=null;this.right=null;this.length=0}}}
 configureLoop(offset,bpm){offset=Math.max(0,Math.min(offset,this.length/this.sr-.15));this.nativeBpm=bpm;const fade=Math.floor(Math.min(this.sr*.025,this.length*.01));this.loopStart=Math.max(0,Math.floor(offset*this.sr)-fade);const available=this.length-this.loopStart-fade;const bar=this.sr*60/bpm*4;const bars=Math.floor(available/bar);this.span=bars>=1?Math.floor(bars*bar):available;}
 align(position,pitch){let ref=null;for(const g of this.grains)if(g.age<this.grainSize&&(!ref||g.age<ref.age))ref=g;if(!ref)return position;let best=position,bestScore=-Infinity;const search=Math.floor(this.sr*.007);for(let shift=-search;shift<=search;shift+=8){let score=0,energyA=0,energyB=0;for(let k=0;k<24;k++){const a=this.read(this.left,ref.pos+k*pitch*3)+this.read(this.right,ref.pos+k*pitch*3),b=this.read(this.left,position+shift+k*pitch*3)+this.read(this.right,position+shift+k*pitch*3);score+=a*b;energyA+=a*a;energyB+=b*b}score/=Math.sqrt(energyA*energyB)+1e-9;score-=Math.abs(shift)/Math.max(1,search)*.008;if(score>bestScore){bestScore=score;best=position+shift}}return best;}
 reset(offset){this.head=offset*this.sr;this.counter=0;this.pendingSync=null;this.correction=0;for(const g of this.grains)g.age=this.grainSize}
 read(data,pos){const len=this.length,fade=Math.floor(Math.min(this.sr*.025,len*.01)),span=this.span||len-fade;pos=((pos%span)+span)%span+fade;const i=Math.floor(pos),f=pos-i;const base=this.loopStart;let v=(data[base+i]||0)*(1-f)+(data[base+i+1]||0)*f;if(pos>span){const t=(pos-span)/fade,j=Math.floor(pos-span);const other=(data[base+j]||0)*(1-f)+(data[base+j+1]||0)*f;v=v*(1-t)+other*t}return v}
 process(inputs,outputs,parameters){const out=outputs[0];if(!out?.length)return true;if(this.resetMsg&&(this.env<=.0005||!this.left)){const d=this.resetMsg;this.resetMsg=null;if(this.left){this.configureLoop(d.offset||0,d.bpm||this.nativeBpm);this.reset(0);this.xf=0}this.startAt=d.startAt||0;this.envT=1;this.env=0}if(!this.left||this.length<2){for(const c of out)c.fill(0);return true}const blockTime=typeof currentTime==='number'?currentTime:0;const sync=this.pendingSync;if(sync&&blockTime>=sync.at){const target=((sync.beat*60/sync.bpm*sync.factor+(blockTime-sync.at)*parameters.speed[0])*this.sr)%this.span;let error=target-this.head;if(error>this.span/2)error-=this.span;if(error< -this.span/2)error+=this.span;if(sync.audible<.03){if(this.prevDirect){this.xfPos=this.head;this.xf=this.xfN}this.head=target;}else this.correction=Math.max(-.015,Math.min(.015,error/(this.sr*2)));this.pendingSync=null;}const speed=parameters.speed[0]*(1+this.correction)*this.sr/sampleRate,pitch=parameters.pitch[0]*this.sr/sampleRate;for(let i=0;i<out[0].length;i++){let l=0,r=0;if((typeof currentTime==='number'?currentTime:0)+i/sampleRate<this.startAt){out[0][i]=0;if(out[1])out[1][i]=0;this.env=0;continue}if(Math.abs(speed-pitch)<.00001){if(!this.prevDirect){let y=null;for(const g of this.grains)if(g.age<this.grainSize&&(!y||g.age<y.age))y=g;if(y){this.xfPos=y.pos;this.xf=this.xfN}}l=this.read(this.left,this.head);r=this.read(this.right,this.head);if(this.xf>0){const k=this.xf/this.xfN;l=l*(1-k)+this.read(this.left,this.xfPos)*k;r=r*(1-k)+this.read(this.right,this.xfPos)*k;this.xfPos+=speed;this.xf--}for(const g of this.grains)g.age=this.grainSize;this.counter=0;this.prevDirect=true}else{this.prevDirect=false;if(this.counter++%this.hop===0){let g=this.grains.find(g=>g.age>=this.grainSize);if(!g)g=this.grains.reduce((a,b)=>a.age>b.age?a:b);g.pos=this.align(this.head,pitch);g.age=0}let sum=0;for(const g of this.grains){if(g.age>=this.grainSize)continue;const w=this.window[g.age++];l+=this.read(this.left,g.pos)*w;r+=this.read(this.right,g.pos)*w;sum+=w;g.pos+=pitch}if(sum>.00001){l/=sum;r/=sum}}this.head=(this.head+speed)%(this.span||this.length);if(this.env<this.envT)this.env=Math.min(this.envT,this.env+this.slew);else if(this.env>this.envT)this.env=Math.max(this.envT,this.env-this.slew);out[0][i]=l*this.env;if(out[1])out[1][i]=r*this.env}return true}
}
registerProcessor('journey-player',JourneyPlayer);
