'use strict';
// One stereo master rack after the track mix: bounded CPU and predictable touch controls.
const trackLevels=[1,1,1,1];
const fxPresets={
 granular:[{name:'Soft cloud',detail:'110 ms grains · scattered stereo',mode:1,mix:.3},{name:'Reverse mist',detail:'Reverse fragments · 200 ms',mode:2,mix:.35},{name:'Prism swarm',detail:'Fifth + octave grains · 85 ms',mode:3,mix:.25},{name:'Frozen constellation',detail:'Capture a moment · hold a cloud',mode:4,mix:.4},{name:'Micro nebula',detail:'45 ms grains · slowed texture',mode:5,mix:.3}],
 delay:[{name:'Tape echo',detail:'Quarter notes · warm feedback',division:1,feedback:.32,tone:3400,spread:1,mix:.25},{name:'Dotted eighth',detail:'Dotted pulse · rhythmic repeats',division:.75,feedback:.38,tone:6500,spread:1,mix:.25},{name:'Ping-pong',detail:'Alternating stereo · half-beat',division:.5,feedback:.44,tone:5200,spread:1.5,mix:.3},{name:'Dub spiral',detail:'Three-quarter beat · dark decay',division:.75,feedback:.66,tone:1500,spread:1.33,mix:.3},{name:'Orbital echoes',detail:'Asymmetric repeats · wide orbit',division:1.25,feedback:.53,tone:4200,spread:1.6,mix:.25}],
 reverb:[{name:'Small room',detail:'0.7 s · close early reflections',decay:.7,pre:.012,style:0,mix:.2},{name:'Luminous plate',detail:'1.8 s · dense, bright tail',decay:1.8,pre:.02,style:1,mix:.28},{name:'Cathedral',detail:'3.8 s · deep, diffuse space',decay:3.8,pre:.055,style:2,mix:.35},{name:'Gated bloom',detail:'0.9 s · swelling, cut-off tail',decay:.9,pre:.025,style:3,mix:.3},{name:'Void chamber',detail:'4.0 s · sparse resonant space',decay:4,pre:.08,style:4,mix:.35}],
 cutoffLfo:[{name:'Lowpass drift',detail:'Slow triangle · gentle breathing',type:'lowpass',hz:2600,depth:1400,q:.7,beats:16,wave:'triangle',mix:1},{name:'Resonant tide',detail:'Sine sweep · resonant lowpass',type:'lowpass',hz:2000,depth:1550,q:3,beats:8,wave:'sine',mix:.8},{name:'Bandpass orbit',detail:'Moving band · focused texture',type:'bandpass',hz:2200,depth:1400,q:1.1,beats:8,wave:'sine',mix:.55},{name:'Stepped transmission',detail:'Square pulse · beat divisions',type:'lowpass',hz:2300,depth:1700,q:1.5,beats:1,wave:'square',mix:.8},{name:'Random beacon',detail:'Sample + hold · wandering cutoff',type:'lowpass',hz:2800,depth:2000,q:2,beats:2,wave:'random',mix:.8}],
 media:[
  {name:'LoFi Tape',detail:'Dusty cassette · wow, hiss, softened highs',hp:70,lp:5200,shelf:2,drive:1.6,wow:[.0022,.6],flut:[.00006,6.5],hiss:.03,crackle:0,rumble:0,bits:16,width:.12,mix:1},
  {name:'Vinyl',detail:'33⅓ rpm warp · surface crackle and rumble',hp:55,lp:8200,shelf:1.5,drive:.7,wow:[.0016,.556],flut:[0,5],hiss:.012,crackle:.55,rumble:.1,bits:16,width:0,mix:1},
  {name:'8-Track',detail:'Cartridge · narrow mono band, heavy drift',hp:130,lp:4200,shelf:0,drive:2.4,wow:[.003,.42],flut:[.00008,8.5],hiss:.045,crackle:0,rumble:0,bits:16,width:.5,mix:1},
  {name:'Reel to Reel',detail:'Studio deck · head bump, tape compression',hp:30,lp:15000,shelf:4,drive:1.2,wow:[.0004,.5],flut:[.00002,5],hiss:.01,crackle:0,rumble:0,bits:16,width:0,mix:1},
  {name:'SP-1200',detail:'12-bit · 26 kHz sampler crunch',hp:40,lp:10500,shelf:1,drive:.9,wow:[0,.5],flut:[0,5],hiss:.006,crackle:0,rumble:0,bits:12,sr:26040,width:0,mix:1}
 ]
};
const effectState=Object.fromEntries(Object.keys(fxPresets).map(k=>[k,{preset:-1,mix:0}]));
let effectsReady=null,selectedSource=0;
function validPerformance(s){return (!s.levels||(Array.isArray(s.levels)&&s.levels.length===4&&s.levels.every(v=>Number.isFinite(v)&&v>=0&&v<=1)))&&(!s.effects||(Object.keys(s.effects).every(k=>fxPresets[k]&&Number.isInteger(s.effects[k].preset)&&s.effects[k].preset>=-1&&s.effects[k].preset<fxPresets[k].length&&Number.isFinite(s.effects[k].mix)&&s.effects[k].mix>=0&&s.effects[k].mix<=1)))}
function performanceData(){return {levels:[...trackLevels],effects:Object.fromEntries(Object.entries(effectState).map(([k,v])=>[k,{...v}]))}}
function restorePerformance(s){if(!validPerformance(s))return;for(let i=0;i<4;i++)trackLevels[i]=s.levels?.[i]??1;for(const k of Object.keys(effectState))Object.assign(effectState[k],s.effects?.[k]||{preset:-1,mix:0});renderTrackMixer();renderEffects();if(audio?.rack)for(const k of Object.keys(effectState))applyEffect(k);}
function glide(param,value,time,tau=.05){if(!param)return;if(param.cancelAndHoldAtTime)param.cancelAndHoldAtTime(time);else param.cancelScheduledValues(time);param.setTargetAtTime(value,time,tau)}
function effectSlot(a){const input=a.createGain(),output=a.createGain(),dry=a.createGain(),wet=a.createGain();dry.gain.value=1;wet.gain.value=0;input.connect(dry);dry.connect(output);wet.connect(output);return{input,output,dry,wet,processor:null}}
function createEffectsRack(a,destination){const input=a.createGain(),slots={};let previous=input;for(const key of Object.keys(effectState)){const s=effectSlot(a);slots[key]=s;previous.connect(s.input);previous=s.output;}previous.connect(destination);
 const d=slots.delay;d.left=a.createDelay(4);d.right=a.createDelay(4);d.fl=a.createBiquadFilter();d.fr=a.createBiquadFilter();d.fl.type=d.fr.type='lowpass';d.fbL=a.createGain();d.fbR=a.createGain();d.fbL.gain.value=d.fbR.gain.value=0;d.split=a.createChannelSplitter(2);d.merge=a.createChannelMerger(2);d.input.connect(d.split);d.split.connect(d.left,0);d.split.connect(d.right,1);d.left.connect(d.fl);d.right.connect(d.fr);d.fl.connect(d.fbL);d.fr.connect(d.fbR);d.fbL.connect(d.right);d.fbR.connect(d.left);d.fl.connect(d.merge,0,0);d.fr.connect(d.merge,0,1);d.merge.connect(d.wet);
 const r=slots.reverb;r.pre=a.createDelay(.2);r.convolver=a.createConvolver();r.convolverB=a.createConvolver();r.convA=a.createGain();r.convB=a.createGain();r.convA.gain.value=1;r.convB.gain.value=0;r.activeBank=0;r.tone=a.createBiquadFilter();r.tone.frequency.value=7800;r.input.connect(r.pre);r.pre.connect(r.convolver);r.pre.connect(r.convolverB);r.convolver.connect(r.convA);r.convolverB.connect(r.convB);r.convA.connect(r.tone);r.convB.connect(r.tone);r.tone.connect(r.wet);
 const f=slots.cutoffLfo;f.filter=a.createBiquadFilter();f.filter.frequency.value=19000;f.lfo=a.createOscillator();f.depth=a.createGain();f.depth.gain.value=0;f.lfo.frequency.value=.1;f.lfo.connect(f.depth);f.depth.connect(f.filter.frequency);f.input.connect(f.filter);f.filter.connect(f.wet);f.lfo.start();

 const m=slots.media;m.hp=a.createBiquadFilter();m.hp.type='highpass';m.hp.frequency.value=20;m.shelf=a.createBiquadFilter();m.shelf.type='lowshelf';m.shelf.frequency.value=90;m.sat=a.createWaveShaper();m.sat.oversample='2x';
 m.wow=a.createDelay(.05);m.wow.delayTime.value=.02;m.wowO=a.createOscillator();m.wowD=a.createGain();m.flutO=a.createOscillator();m.flutD=a.createGain();m.wowD.gain.value=m.flutD.gain.value=0;m.wowO.frequency.value=.5;m.flutO.frequency.value=6;m.wowO.connect(m.wowD);m.wowD.connect(m.wow.delayTime);m.flutO.connect(m.flutD);m.flutD.connect(m.wow.delayTime);m.wowO.start();m.flutO.start();
 m.crushIn=a.createGain();m.crushOut=a.createGain();m.crushIn.connect(m.crushOut);m.crush=null;
 m.lp=a.createBiquadFilter();m.lp.type='lowpass';m.lp.frequency.value=20000;m.lp.Q.value=.5;
 m.split=a.createChannelSplitter(2);m.merge=a.createChannelMerger(2);m.ll=a.createGain();m.lr=a.createGain();m.rl=a.createGain();m.rr=a.createGain();m.ll.gain.value=m.rr.gain.value=1;m.lr.gain.value=m.rl.gain.value=0;
 m.input.connect(m.hp);m.hp.connect(m.shelf);m.shelf.connect(m.sat);m.sat.connect(m.wow);m.wow.connect(m.crushIn);m.crushOut.connect(m.lp);m.lp.connect(m.split);
 m.split.connect(m.ll,0);m.split.connect(m.lr,0);m.split.connect(m.rl,1);m.split.connect(m.rr,1);m.ll.connect(m.merge,0,0);m.rl.connect(m.merge,0,0);m.lr.connect(m.merge,0,1);m.rr.connect(m.merge,0,1);m.merge.connect(m.wet);
 // noise bed: tape hiss, vinyl rumble and surface crackle. Gains stay at 0 until a preset asks for them.
 const sr=a.sampleRate,wl=sr*3,wb=a.createBuffer(2,wl,sr);let ns=7919;const rnd=()=>{ns=(Math.imul(ns,1664525)+1013904223)>>>0;return ns/4294967296};for(let c=0;c<2;c++){const d=wb.getChannelData(c);for(let i=0;i<wl;i++)d[i]=rnd()*2-1}
 m.noise=a.createBufferSource();m.noise.buffer=wb;m.noise.loop=true;m.hissHP=a.createBiquadFilter();m.hissHP.type='highpass';m.hissHP.frequency.value=1800;m.hissG=a.createGain();m.rumbleLP=a.createBiquadFilter();m.rumbleLP.type='lowpass';m.rumbleLP.frequency.value=55;m.rumbleG=a.createGain();m.hissG.gain.value=m.rumbleG.gain.value=0;
 m.noise.connect(m.hissHP);m.hissHP.connect(m.hissG);m.hissG.connect(m.wet);m.noise.connect(m.rumbleLP);m.rumbleLP.connect(m.rumbleG);m.rumbleG.connect(m.wet);m.noise.start();
 const cl=sr*6,cb=a.createBuffer(2,cl,sr);for(let c=0;c<2;c++){const d=cb.getChannelData(c);for(let i=0;i<cl;i++){d[i]=(rnd()*2-1)*.006;if(rnd()<7/sr){const amp=(.25+rnd()*.75)*(rnd()<.5?-1:1),len=Math.floor(sr*(.0008+rnd()*.003));for(let j=0;j<len&&i+j<cl;j++)d[i+j]+=amp*Math.exp(-j/(len*.35))*(j%2?-.6:1)}else if(rnd()<45/sr)d[i]+=(rnd()*2-1)*.14}}
 m.crack=a.createBufferSource();m.crack.buffer=cb;m.crack.loop=true;m.crackG=a.createGain();m.crackG.gain.value=0;m.crack.connect(m.crackG);m.crackG.connect(m.wet);m.crack.start();
 return {input,slots,lastBpm:0,lastRandomBeat:-1};}
async function initializeEffects(){if(!audio?.rack)return;if(!effectsReady)effectsReady=(async()=>{try{await audio.a.audioWorklet.addModule('./granular-fx.js');const slot=audio.rack.slots.granular;slot.processor=new AudioWorkletNode(audio.a,'continuum-granular',{numberOfInputs:1,numberOfOutputs:1,outputChannelCount:[2]});slot.input.connect(slot.processor);slot.processor.connect(slot.wet);slot.processor.onprocessorerror=()=>{effectState.granular.preset=-1;applyEffect('granular');renderEffects();message('Granular stopped. Other effects remain available.')};}catch{effectState.granular.preset=-1;message('Granular is unavailable in this browser. Delay, Reverb and Cutoff remain available.')}try{await audio.a.audioWorklet.addModule('./lofi-fx.js');const m=audio.rack.slots.media;m.crush=new AudioWorkletNode(audio.a,'continuum-crush',{numberOfInputs:1,numberOfOutputs:1,outputChannelCount:[2]});m.crushIn.disconnect(m.crushOut);m.crushIn.connect(m.crush);m.crush.connect(m.crushOut)}catch{}for(const k of Object.keys(effectState))applyEffect(k);renderEffects()})();await effectsReady;}
function makeImpulse(a,p){const sr=a.sampleRate,length=Math.ceil(sr*p.decay),b=a.createBuffer(2,length,sr);let seed=24809;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};for(let c=0;c<2;c++){const data=b.getChannelData(c);let smooth=0;for(let i=0;i<length;i++){const t=i/length,n=random()*2-1;let env=Math.pow(1-t,p.style===2?2.8:p.style===1?2:3.5);smooth=smooth*.75+n*.25;let v=p.style===1?n:smooth;if(p.style===3)env=Math.sin(Math.PI*Math.min(1,t*1.4))*(t<.82?1:Math.max(0,(1-t)/.18));if(p.style===4){v=n*(random()<.035?3:0)+Math.sin(i/sr*2*Math.PI*(c?173:137))*.06;env=Math.pow(1-t,2.5)}data[i]=v*env*.45;}if(p.style===0){for(const seconds of [.017,.029,.043,.061]){const j=Math.floor((seconds+c*.003)*sr);if(j<length)data[j]+=.55}}}return b;}
function applyEffect(key){if(!audio?.rack)return;const s=audio.rack.slots[key],v=effectState[key],p=fxPresets[key][v.preset],t=audio.a.currentTime;const mix=p?v.mix:0;glide(s.dry.gain,1-mix,t);glide(s.wet.gain,mix,t);if(key==='granular'){if(s.processor)glide(s.processor.parameters.get('mode'),p?.mode||0,t,.001);return}
 if(key==='delay'){glide(s.fbL.gain,p?.feedback||0,t,.1);glide(s.fbR.gain,p?.feedback||0,t,.1);if(p){glide(s.fl.frequency,p.tone,t);glide(s.fr.frequency,p.tone,t);}audio.rack.lastBpm=0;}
 if(key==='reverb'&&p){if(s.preset!==v.preset){const next=s.activeBank===0?1:0;(next?s.convolverB:s.convolver).buffer=makeImpulse(audio.a,p);glide(s.convA.gain,next===0?1:0,t,.08);glide(s.convB.gain,next===1?1:0,t,.08);s.activeBank=next;s.preset=v.preset;}glide(s.pre.delayTime,p.pre,t);glide(s.tone.frequency,p.style===4?3600:p.style===1?9500:6400,t);}
 if(key==='cutoffLfo'){if(p){s.filter.type=p.type;glide(s.filter.frequency,p.hz,t,.12);glide(s.filter.Q,p.q,t);if(p.wave!=='random')s.lfo.type=p.wave;glide(s.depth.gain,p.wave==='random'?0:p.depth,t,.15);}else glide(s.depth.gain,0,t);audio.rack.lastBpm=0;}
 if(key==='media'){const g=(par,val,tau)=>glide(par,val,t,tau||.1);
  if(p){g(s.hp.frequency,p.hp);g(s.lp.frequency,p.lp);g(s.shelf.gain,p.shelf);s.sat.curve=satCurve(p.drive);g(s.wowD.gain,p.wow[0],.15);g(s.wowO.frequency,p.wow[1],.2);g(s.flutD.gain,p.flut[0],.15);g(s.flutO.frequency,p.flut[1],.2);g(s.hissG.gain,p.hiss);g(s.crackG.gain,p.crackle);g(s.rumbleG.gain,p.rumble);
   const c=p.width;g(s.ll.gain,1-c);g(s.rr.gain,1-c);g(s.lr.gain,c);g(s.rl.gain,c);
   if(s.crush){g(s.crush.parameters.get('bits'),p.bits,.01);g(s.crush.parameters.get('rate'),p.sr?Math.min(1,p.sr/audio.a.sampleRate):1,.01)}}
  else{g(s.wowD.gain,0);g(s.flutD.gain,0);g(s.hissG.gain,0);g(s.crackG.gain,0);g(s.rumbleG.gain,0)}}
 updateEffectsClock();}
const satCache={};function satCurve(drive){if(!drive)return null;const key=drive.toFixed(2);if(satCache[key])return satCache[key];const n=2048,c=new Float32Array(n),norm=Math.tanh(drive*1.2);for(let i=0;i<n;i++){const x=i/(n-1)*2-1;c[i]=Math.tanh(drive*1.2*x)/norm}return satCache[key]=c}
function updateEffectsClock(){if(!audio?.rack||audio.a.state!=='running')return;const rack=audio.rack,t=audio.a.currentTime,bpm=audio.bpm,changed=Math.abs(bpm-rack.lastBpm)>.5;
 if(changed){rack.lastBpm=bpm;const d=fxPresets.delay[effectState.delay.preset];if(d){glide(rack.slots.delay.left.delayTime,Math.min(3.8,60/bpm*d.division),t,.2);glide(rack.slots.delay.right.delayTime,Math.min(3.8,60/bpm*d.division*d.spread),t,.2);}const f=fxPresets.cutoffLfo[effectState.cutoffLfo.preset];if(f&&f.wave!=='random')glide(rack.slots.cutoffLfo.lfo.frequency,bpm/60/f.beats,t,.1);}
 const p=fxPresets.cutoffLfo[effectState.cutoffLfo.preset];if(p?.wave==='random'){const beat=Math.floor(audio.beatPosition()/p.beats);if(beat!==rack.lastRandomBeat){rack.lastRandomBeat=beat;const r=rng((seed^Math.imul(beat,9871))>>>0);glide(rack.slots.cutoffLfo.filter.frequency,p.hz+(r()*2-1)*p.depth,t,.06);}}
}
function renderTrackMixer(){const root=$('trackMixer');if(!root)return;root.replaceChildren();for(let i=0;i<4;i++){const card=document.createElement('article');card.className='track-strip';card.style.setProperty('--color',palettes[i]);const top=document.createElement('button');top.className='source-select';top.setAttribute('aria-pressed',selectedSource===i);top.innerHTML='<span class="strip-code">SOURCE / '+String(i+1).padStart(2,'0')+'</span>';const title=document.createElement('strong');title.textContent=worlds[i].name;top.append(title);top.onclick=()=>{selectedSource=i;point={x:nodes[i].x,y:nodes[i].y};stopJourney();renderTrackMixer()};const line=document.createElement('label');line.className='track-fader';line.textContent='LEVEL';const out=document.createElement('output');out.textContent=Math.round(trackLevels[i]*100)+'%';const slider=document.createElement('input');slider.type='range';slider.min=0;slider.max=100;slider.value=Math.round(trackLevels[i]*100);slider.setAttribute('aria-label',worlds[i].name+' track volume');slider.oninput=()=>{trackLevels[i]=+slider.value/100;out.textContent=slider.value+'%';if(audio?.routes[i]?.levelGain)glide(audio.routes[i].levelGain.gain,trackLevels[i],audio.a.currentTime);};line.append(out,slider);const meter=document.createElement('div');meter.className='strip-meter';meter.id='strip-meter-'+i;meter.setAttribute('aria-hidden','true');card.append(top,line,meter);root.append(card)}}
async function chooseEffect(k,index){if(!enabled)await enter();if(!enabled)return;if(k==='granular'&&!audio.rack?.slots.granular.processor){message('Granular is unavailable in this browser.');return}effectState[k].preset=index;effectState[k].mix=index<0?0:fxPresets[k][index].mix;applyEffect(k);renderEffects();if(typeof saveWorkingSession==='function')saveWorkingSession();}
function renderEffects(){const root=$('effectsControls');if(!root)return;root.replaceChildren();const labels={granular:'GRANULAR',delay:'DELAY',reverb:'REVERB',cutoffLfo:'CUTOFF + LFO',media:'LO-FI MEDIA'};Object.keys(fxPresets).forEach((key,n)=>{const card=document.createElement('article');card.className='fx-card';const head=document.createElement('div');head.className='fx-card-head';head.innerHTML='<span class="fx-number">0'+(n+1)+'</span><h3>'+labels[key]+'</h3>';const badge=document.createElement('span');badge.className='fx-status';badge.textContent=effectState[key].preset<0?'BYPASS':'ACTIVE';head.append(badge);const choices=document.createElement('div');choices.className='preset-grid';[{name:'Bypass'},...fxPresets[key]].forEach((p,i)=>{const b=document.createElement('button');b.className='preset-pad';b.textContent=p.name;b.setAttribute('aria-pressed',effectState[key].preset===i-1);b.onclick=()=>chooseEffect(key,i-1);choices.append(b)});const detail=document.createElement('p');detail.className='preset-detail';detail.textContent=fxPresets[key][effectState[key].preset]?.detail||'Original signal passes through.';const label=document.createElement('label');label.className='fx-mix';label.textContent='DRY / WET';const out=document.createElement('output');out.textContent=Math.round(effectState[key].mix*100)+'%';const slider=document.createElement('input');slider.type='range';slider.min=0;slider.max=100;slider.value=Math.round(effectState[key].mix*100);slider.disabled=effectState[key].preset<0;slider.setAttribute('aria-label',labels[key]+' effect mix');slider.oninput=()=>{effectState[key].mix=+slider.value/100;out.textContent=slider.value+'%';const s=audio?.rack?.slots[key];if(s){glide(s.dry.gain,1-effectState[key].mix,audio.a.currentTime);glide(s.wet.gain,effectState[key].mix,audio.a.currentTime)}};label.append(out,slider);card.append(head,choices,detail,label);root.append(card)});}
renderTrackMixer();renderEffects();
