'use strict';
const transitionSettings={focus:true,guard:true,spatial:.32};
function family(mode){return ['Minor','Dorian'].includes(mode)?'minor':'major'}
function musicalMix(p){const raw=blend(p);if(!transitionSettings.focus)return raw;const ranked=raw.map((w,i)=>({w,i})).sort((a,b)=>b.w-a.w),a=ranked[0],b=ranked[1];const conflict=transitionSettings.guard&&family(worlds[a.i].mode)!==family(worlds[b.i].mode);const power=conflict?2.4:1.25,wa=Math.pow(a.w,power),wb=Math.pow(b.w,power),sum=wa+wb;return raw.map((_,i)=>i===a.i?wa/sum:i===b.i?wb/sum:0)}
function guardedGain(i){if(!transitionSettings.guard)return 1;let conflict=0;for(let j=0;j<4;j++)if(i!==j&&family(worlds[i].mode)!==family(worlds[j].mode))conflict+=weights[j];return 1-.55*Math.min(1,4*weights[i]*conflict)}
function transitionLabel(){const ranked=weights.map((w,i)=>({w,i})).sort((a,b)=>b.w-a.w);if(ranked[1].w<.04)return 'IN ORBIT';return family(worlds[ranked[0].i].mode)!==family(worlds[ranked[1].i].mode)&&transitionSettings.guard?'SCALE-AWARE HANDOFF':'HARMONIC CROSSFADE'}
function createTrackRoute(a,master,index){const input=a.createGain(),levelGain=a.createGain(),slots={},analyser=a.createAnalyser(),distanceFilter=a.createBiquadFilter(),pan=a.createStereoPanner(),dry=a.createGain(),space=a.createGain();input.connect(levelGain);levelGain.gain.value=typeof trackLevels==='undefined'?1:trackLevels[index];let previous=levelGain;for(const name of ['granular','delay','reverb','cutoffLfo']){const inlet=a.createGain(),outlet=a.createGain();previous.connect(inlet);inlet.connect(outlet);slots[name]={input:inlet,output:outlet,bypassed:true,processor:null};previous=outlet}previous.connect(analyser);analyser.fftSize=128;analyser.connect(distanceFilter);distanceFilter.type='lowpass';distanceFilter.frequency.value=19000;distanceFilter.Q.value=.4;distanceFilter.connect(pan);pan.connect(dry);dry.gain.value=1;dry.connect(master);let hrtf=null;if(a.createPanner){hrtf=a.createPanner();hrtf.panningModel='HRTF';hrtf.distanceModel='linear';hrtf.rolloffFactor=0;hrtf.refDistance=1;hrtf.maxDistance=10;distanceFilter.connect(hrtf);hrtf.connect(space);space.gain.value=0;space.connect(master)}return{input,levelGain,slots,analyser,distanceFilter,pan,dry,space,hrtf,meter:new Uint8Array(128),level:0,index}}
function updateSpatialScene(dt){if(!audio?.routes)return;const time=audio.a.currentTime,amount=transitionSettings.spatial;audio.routes.forEach((r,i)=>{const dx=(nodes[i].x-point.x)*2,dy=(nodes[i].y-point.y)*2,distance=Math.hypot(dx,dy);r.pan.pan.setTargetAtTime(Math.max(-.65,Math.min(.65,dx*amount)),time,.35);r.distanceFilter.frequency.setTargetAtTime(19000-(Math.min(1,distance)*amount*8500),time,.5);r.dry.gain.setTargetAtTime(r.hrtf?1-amount*.18:1,time,.3);r.space.gain.setTargetAtTime(r.hrtf?amount*.18:0,time,.3);if(r.hrtf){if(r.hrtf.positionX){r.hrtf.positionX.setTargetAtTime(dx*2,time,.4);r.hrtf.positionY.setTargetAtTime(0,time,.4);r.hrtf.positionZ.setTargetAtTime(dy*2-.5,time,.4)}else r.hrtf.setPosition(dx*2,0,dy*2-.5)}})}
function updateSceneMeters(){if(!audio?.routes)return;audio.routes.forEach((r,i)=>{r.analyser.getByteTimeDomainData(r.meter);let energy=0;for(const v of r.meter)energy+=((v-128)/128)**2;r.level=Math.min(1,Math.sqrt(energy/r.meter.length)*4);const strip=$('strip-meter-'+i);if(strip)strip.style.setProperty('--level',r.level*100+'%');const meter=$('level-'+i);if(meter)meter.style.setProperty('--level',r.level*100+'%')})}
function syncImportedBeat(beat,at){if(typeof audioMode==='undefined'||audioMode==='original')return;for(let i=0;i<4;i++){const track=audioSlots[i];if(!track?.ready)continue;const speed=matchedSpeed(audio.bpm,track.bpm);const factor=speed*track.bpm/audio.bpm;track.player.port.postMessage({type:'sync',beat,at,bpm:track.bpm,factor,audible:weights[i]})}}
function matchedSpeed(bpm,native){let speed=bpm/native;while(speed>1.75)speed/=2;while(speed<.6)speed*=2;return speed}
function restoreSceneSettings(s){transitionSettings.focus=s.scene?.focus??true;transitionSettings.guard=s.scene?.guard??true;transitionSettings.spatial=s.scene?.spatial??.32;$('focusBlend').checked=transitionSettings.focus;$('harmonyGuard').checked=transitionSettings.guard;$('spatialAmount').value=Math.round(transitionSettings.spatial*100);$('spatialValue').textContent=Math.round(transitionSettings.spatial*100)+'%'}
$('focusBlend').onchange=()=>{transitionSettings.focus=$('focusBlend').checked;message(transitionSettings.focus?'Focused blends keep the two nearest soundscapes in the transition.':'Layered blends allow all four soundscapes to overlap.')};$('harmonyGuard').onchange=()=>{transitionSettings.guard=$('harmonyGuard').checked;message(transitionSettings.guard?'Harmony guard narrows incompatible scale overlaps and eases their combined level.':'Harmony guard bypassed.')};$('spatialAmount').oninput=()=>{transitionSettings.spatial=+$('spatialAmount').value/100;$('spatialValue').textContent=$('spatialAmount').value+'%'};
