#!/usr/bin/env node
// Generates docs/PARAMETERS.md (parameter matrix) and docs/QA-REPORT.md (QA results) from kits/ and qa/<kit>/qa.json.
import fs from 'node:fs'; import path from 'node:path';
import { loadKit } from './harness.mjs';
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const ids = fs.readdirSync(path.join(root, 'src')).filter(d => /^\d\d-/.test(d)).map(d => d.replace(/^\d\d-/, ''));
let P = '# Parameter matrix\n\nGenerated by `tools/gen-docs.mjs` from the built manifests. Defaults are the hero values; per-style overrides are listed under each kit. Ranges are in scene units (short side = 1) unless a unit is shown.\n\n';
let Q = '# QA report\n\nGenerated from `qa/<kit>/qa.json` (written by `tools/qa.mjs qa`). Renderer: headless Chromium, SwiftShader software GL, 180x320. Metrics are defined in `tools/qa.mjs`:\n\n- **Delta0**: mean absolute 8-bit difference between phase 0 and phase 1 (identical seed and parameters). `0` means bit-identical.\n- **Seam x**: the larger of the two one-frame steps straddling the wrap (60 fps, 12 s loop), divided by the median one-frame step of the loop. About 1 means the seam is as smooth as any other frame; the playbook fails at Delta0 > 1.5 on its own metric, which is not available outside AgentMotif, so this is reported as defined here.\n- **Pop x**: maximum one-frame step divided by the median step among moving frames (holds excluded). Target < 3, fail > 6.\n- **Flash tiles**: tiles of a 4x4 grid exceeding 3 flash pairs per second in the worst case (1 s loop at 4x tempo, limiter on), WCAG-style 0.1 relative-luminance swing. < 4 passes, 1-3 is a warning.\n- **Exposure spread**: max/min mean luminance across Live/Balanced/Export at one phase; target within 15%.\n\n';
for (const id of ids) {
  const { kit, report } = loadKit(path.join(root, 'kits', id));
  const s0 = kit.styles[0]; const union = {}; for (const st of kit.styles) for (const [k, sp] of Object.entries(st.params)) (union[k] ||= { sp, n: 0 }).n++;
  P += `## ${kit.name}\n\n${kit.description}\n\nControls are shown per style: a control a style does not use is removed from that style (checked by tools/qa.mjs controls). n/9 is how many styles carry it.\n\n| Key | Label | Type | Range | Hero default | Group | Styles | Hint |\n|---|---|---|---|---|---|---|---|\n`;
  for (const [k, { sp: s, n }] of Object.entries(union)) P += `| \`${k}\` | ${s.label} | ${s.type} | ${s.type === 'select' ? s.options.map(o => o.v).join(' / ') : `${s.min} – ${s.max}${s.log ? ' (log)' : ''}${s.unit ? ' ' + s.unit : ''}`} | ${(s0.params[k] || s).def} | ${s.group || ''} | ${n}/9 | ${(s.hint || '').replace(/\|/g, '/')} |\n`;
  P += '\nPer-style defaults that differ from the hero:\n\n';
  for (const st of kit.styles.slice(1)) { const diffs = Object.entries(st.params).filter(([k, s]) => !s0.params[k] || JSON.stringify(s.def) !== JSON.stringify(s0.params[k].def)).map(([k, s]) => `${k}=${s.def}`).concat(Object.keys(s0.params).filter(k => !st.params[k]).map(k => `no ${k}`)); P += `- **${st.name}** (palette \`${st.palette}\`): ${diffs.join(', ') || 'hero defaults'}\n`; }
  P += '\n';
  const qf = path.join(root, 'qa', id, 'qa.json');
  Q += `## ${kit.name}\n\nPass graph: ${s0.graph ? 'scene → glow A (0.25) → glow B (0.125) → output (1.0)' : 'single full-resolution analytic pass'}. Worst-case static budget: ${Math.max(...report.entries.map(e => e.iterations)).toFixed(0)} loop iterations/px, ${Math.max(...report.entries.map(e => e.fetches)).toFixed(0)} fetches/px (limits 32768 / 2048).\n\n`;
  if (fs.existsSync(qf)) { const q = JSON.parse(fs.readFileSync(qf, 'utf8')); Q += '| Style | Delta0 | Seam x | Pop x | Flash tiles | Exposure spread | Verdict |\n|---|---|---|---|---|---|---|\n';
    for (const r of q.results) { const v = [r.seamRatio <= 3 ? '' : 'SEAM', r.popRatio <= 3 ? '' : r.popRatio <= 6 ? 'pop warn' : 'POP', r.flashTilesOver3 === 0 ? '' : r.flashTilesOver3 < 4 ? 'flash warn' : 'FLASH', r.exposureSpread === undefined || r.exposureSpread <= 0.15 ? '' : 'EXPOSURE'].filter(Boolean).join(', ') || 'pass';
      Q += `| ${r.id} | ${r.delta0_p1} | ${r.seamRatio} | ${r.popRatio} | ${r.flashTilesOver3} | ${r.exposureSpread === undefined ? 'n/a (no quality-dependent pass)' : (r.exposureSpread * 100).toFixed(1) + '%'} | ${v} |\n`; } Q += '\n'; }
  else Q += '_QA not run yet._\n\n';
}
fs.writeFileSync(path.join(root, 'docs/PARAMETERS.md'), P); fs.writeFileSync(path.join(root, 'docs/QA-REPORT.md'), Q); console.log('wrote docs/PARAMETERS.md, docs/QA-REPORT.md');
