// Regenerates sdk/motif-kit-sdk/lib/kit-gl.js from the app modules, so the SDK validates and previews kits with
// exactly the app's rules (motif-kit@1/@2/@3 validation, static GLSL analysis, WebGL2 runtime, text-input atlas).
//   node tools/sdk-sync.mjs           write the SDK copy
//   node tools/sdk-sync.mjs --check   fail if the SDK copy is stale (used by tests)
// The file is evaluated by the CLI as `new Function(source)()`: module bodies, then one `return`.
import fs from 'node:fs'; import path from 'node:path';
const root = path.resolve(import.meta.dirname, '..');
const mod = f => fs.readFileSync(path.join(root, 'src-v5/modules', f), 'utf8');
const out = path.join(root, 'sdk/motif-kit-sdk/lib/kit-gl.js');
const text = `// GENERATED by tools/sdk-sync.mjs from src-v5/modules/04-kit-gl.js + 04a-kit-sandbox.js + 04b-text-atlas.js. Do not edit.
// DOM-free validation (motif-kit@1, @2 and @3, static GLSL analysis) + the WebGL2 kit runtime + the text-input atlas
// rasterizer, as the app runs them. textAtlas is the app's 04b module (OffscreenCanvas; browser only).
${mod('04-kit-gl.js')}
${mod('04a-kit-sandbox.js')}
${mod('04b-text-atlas.js')}
return Object.assign({}, __m_kit_gl, __m_kit_sandbox, { textAtlas: __m_text_atlas, validateKit: __m_kit_sandbox.validate, validateKitV1: __m_kit_gl.validateKit, KIT_FORMAT: __m_kit_sandbox.KIT_FORMAT_3 });
`;
if (process.argv.includes('--check')) {
  if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== text) { console.error('sdk/motif-kit-sdk/lib/kit-gl.js is stale: run node tools/sdk-sync.mjs'); process.exit(1); }
  console.log('SDK kit-gl.js up to date');
} else { fs.writeFileSync(out, text); console.log(`wrote ${path.relative(root, out)} (${text.length.toLocaleString()} bytes)`); }
