// Kit → Metal package. Validates with the same code as the web runtime, assembles each pass exactly like the
// WebGL build (prelude + params + media inputs + kit common + pass), translates that GLSL to MSL, and writes a
// Swift package that renders it.
import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { translate, lintMsl } from './translate.mjs';
import { MSL_HEADER, entryPoint, structConstructor } from './msl-header.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));

export function loadKitGl(file = path.join(here, 'kit-gl.js')) {
  return new Function(fs.readFileSync(file, 'utf8'))();
}

const ident = s => s.replace(/[^A-Za-z0-9]+/g, '_');
const pascal = s => s.split(/[^A-Za-z0-9]+/).filter(Boolean).map(w => w[0].toUpperCase() + w.slice(1)).join('');
const swiftRaw = s => { let h = 1; while (s.includes('"""' + '#'.repeat(h))) h++; const f = '#'.repeat(h); return `${f}"""\n${s}\n"""${f}`; };

// Params in declaration order, each with the slot index it occupies in the float buffer the runtime uploads.
function paramTable(params) {
  return Object.entries(params).filter(([, p]) => p.type !== 'text').map(([key, p], index) => ({ key, index, ...p }));
}

/** Translate one pass of one style to a self-contained .metal source. */
export function convertPass(KG, kit, style, passIndex, opts = {}) {
  const warnings = [];
  const final = passIndex === style.passes.length - 1;
  const { src: web } = KG.buildSource(style.passes[passIndex].src, kit.common, style.params, final, style.inputs);
  // Take the web source apart: drop the web-only main(), keep prelude + params + inputs + common + pass.
  let glsl = web.slice(0, web.length - KG.MAIN_FINAL.length * (final ? 1 : 0) - KG.MAIN_PASS.length * (final ? 0 : 1));
  glsl = glsl.replace(/^#version[^\n]*\n/, '').replace(/^out vec4 M_out;\n/m, '') + '\nuniform vec4 gl_FragCoord;\n';
  // dither + sRGB come from the web's final main() so the Metal build can never drift from it.
  const tail = KG.MAIN_FINAL.slice(0, KG.MAIN_FINAL.indexOf('void main'));
  const t = translate(glsl + '\n' + tail, { warn: m => warnings.push(`${style.id} pass ${passIndex + 1}: ${m}`) });
  const struct = `MPass_${ident(kit.id)}_${ident(style.localId)}_p${passIndex}`;
  const fn = `mfs_${ident(kit.id)}_${ident(style.localId)}_p${passIndex}`;
  const params = paramTable(style.params);
  const msl = [
    `// Generated by motif-metal from ${kit.id}/${style.localId}, pass ${passIndex + 1} of ${style.passes.length} (${style.passes[passIndex].file}). Do not edit.`,
    MSL_HEADER,
    '// ---- hoisted: macros, structs, program-scope constants ---------------------------------------------------------',
    t.hoisted,
    `\n// ---- pass: every function is a member so uniforms read as plain identifiers --------------------------------------`,
    `struct ${struct} {\n${t.members}\n${structConstructor(struct, style.inputs)}\n};`,
    entryPoint({ fn, struct, params, inputs: style.inputs, passIndex }),
  ].join('\n');
  const problems = lintMsl(msl);
  problems.forEach(p => warnings.push(`${style.id} pass ${passIndex + 1}: ${p}`));
  return { fn, struct, msl, warnings, problems };
}

export function convertKit(KG, raw, opts = {}) {
  const v = KG.validateKit(raw.manifest, raw.files);
  if (!v.ok) { const e = new Error('Kit failed validation:\n  ' + v.errors.join('\n  ')); e.validation = v; throw e; }
  const kit = v.kit, warnings = [...v.warnings], files = {}, sources = {};
  const target = pascal(kit.id) + 'MotifKit', kitType = pascal(kit.id) + 'Kit';
  const json = {
    format: 'motif-metal@1', source: 'motif-kit@1', sdk: KG.SDK_VERSION,
    id: kit.id, name: kit.name, version: kit.version, author: kit.author, description: kit.description, accent: kit.accent, license: kit.license,
    palettes: kit.palettes.map(p => ({ id: p.id.slice(kit.id.length + 1), name: p.name, bg: p.bg, ink: p.ink, a: p.a })),
    styles: [],
  };
  let failed = 0;
  for (const st of kit.styles) {
    const passes = [];
    for (let i = 0; i < st.passes.length; i++) {
      let r;
      try { r = convertPass(KG, kit, st, i, opts); } catch (e) { failed++; warnings.push(`${st.id} pass ${i + 1}: ${e.message}`); continue; }
      warnings.push(...r.warnings); if (r.problems.length) failed++;
      const key = `${ident(kit.id)}_${ident(st.localId)}_p${i}`;
      files[`Metal/${key}.metal`] = r.msl; sources[key] = r.msl;
      passes.push({ function: r.fn, source: key, scale: st.passes[i].scale });
    }
    json.styles.push({
      id: st.id, localId: st.localId, name: st.name, blurb: st.blurb, group: st.group, tags: st.tags,
      palette: st.palette ? st.palette.slice(kit.id.length + 1) : null, flash: st.flash, cost: st.cost,
      passes, inputs: st.inputs.map(q => ({ id: q.id, type: q.type, label: q.label, fit: q.fit, hint: q.hint, ...(q.implicit ? { implicit: true } : {}) })),
      params: paramTable(st.params).map(p => {
        const o = { key: p.key, index: p.index, type: p.type, label: p.label, def: p.def };
        for (const k of ['min', 'max', 'step', 'unit', 'group', 'hint', 'mutate', 'log', 'randMax', 'show', 'part']) if (p[k] !== undefined) o[k] = p[k];
        if (p.options) o.options = p.options;
        return o;
      }),
    });
  }
  const jsonText = JSON.stringify(json, null, 2) + '\n';
  files['kit.json'] = jsonText;

  // Swift: kit definition + embedded sources (so `swift build` works with no Metal toolchain; the runtime
  // compiles each pass on first use and a precompiled metallib can replace it, see build-metallib.sh).
  const keys = Object.keys(sources).sort();
  files[`Sources/${target}/${kitType}.swift`] = `// Generated by motif-metal from ${kit.id} ${kit.version}. Do not edit.
import Foundation
import MotifMetal

public enum ${kitType} {
    /// The kit: styles, parameters, palettes and the Metal source for every pass.
    public static let definition: MotifKitDefinition = {
        do { return try MotifKitDefinition(json: Data(kitJSON.utf8), sources: shaderSources) }
        catch { fatalError("${kit.id}: \\(error)") }
    }()

    static let kitJSON = ${swiftRaw(jsonText.trim())}

    static let shaderSources: [String: String] = {
        var s = [String: String]()
${keys.map(k => `        s["${k}"] = ${swiftRaw(sources[k])}`).join('\n')}
        return s
    }()
}
`;
  const rt = opts.runtime || '../../tools/motif-metal/swift/MotifMetal';
  const dep = /^https?:|^git@/.test(rt) ? `.package(url: "${rt}", from: "1.0.0")` : `.package(path: "${rt}")`;
  files['Package.swift'] = `// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "${target}",
    platforms: [.macOS(.v12), .iOS(.v15)],
    products: [.library(name: "${target}", targets: ["${target}"])],
    dependencies: [${dep}],
    targets: [
        .target(name: "${target}", dependencies: [.product(name: "MotifMetal", package: "MotifMetal")]),
        .testTarget(name: "${target}Tests", dependencies: ["${target}", .product(name: "MotifMetal", package: "MotifMetal")]),
    ]
)
`;
  files[`Tests/${target}Tests/ShaderTests.swift`] = `import XCTest
import CoreGraphics
import Metal
import MotifMetal
@testable import ${target}

/// Run on a Mac (\`swift test\`) or in Xcode: compiles every pass with the real Metal compiler and renders it.
final class ShaderTests: XCTestCase {
    private func bytes(_ image: CGImage) -> [UInt8] {
        guard let d = image.dataProvider?.data else { return [] }
        return [UInt8](d as Data)
    }

    func testEveryStyleCompilesAndRenders() throws {
        guard MTLCreateSystemDefaultDevice() != nil else { throw XCTSkip("No Metal device") }
        let renderer = try MotifRenderer()
        let kit = ${kitType}.definition
        XCTAssertEqual(kit.styles.count, ${kit.styles.length})
        for style in kit.styles {
            let state = MotifRenderState(phase: 0.37, loopSeconds: 6, seed: 417)
            let image = try renderer.renderImage(kit: kit, style: style, state: state, width: 96, height: 54)
            XCTAssertEqual(image.width, 96, style.id)
            XCTAssertFalse(bytes(image).isEmpty, style.id)
        }
    }

    /// Frame 0 and the frame at the loop length must match: every loop closes exactly.
    func testLoopsClose() throws {
        guard MTLCreateSystemDefaultDevice() != nil else { throw XCTSkip("No Metal device") }
        let renderer = try MotifRenderer()
        let kit = ${kitType}.definition
        for style in kit.styles {
            var a = MotifRenderState(phase: 0, loopSeconds: 6, seed: 417)
            var b = a
            a.phase = 0; b.phase = 1
            let x = bytes(try renderer.renderImage(kit: kit, style: style, state: a, width: 64, height: 36))
            let y = bytes(try renderer.renderImage(kit: kit, style: style, state: b, width: 64, height: 36))
            XCTAssertEqual(x.count, y.count)
            var sum = 0
            for i in 0..<min(x.count, y.count) { sum += abs(Int(x[i]) - Int(y[i])) }
            let mean = Double(sum) / Double(max(1, x.count))
            XCTAssertLessThan(mean, 2.0, "\\(style.id) does not close its loop (mean diff \\(mean))")
        }
    }
}
`;
  files[`${kit.id}-${kit.version}.metalkit`] = JSON.stringify({ format: 'motif-metal@1', kit: json, sources }) + '\n';
  files['build-metallib.sh'] = `#!/bin/sh
# Optional: precompile every pass into metallibs (macOS and iPadOS). The Swift package works without this.
# Needs Xcode: xcrun metal. Fast math is off so isnan() and the photosensitive limiter behave as on the web.
set -e
cd "$(dirname "$0")"
mkdir -p build
for sdk in macosx iphoneos; do
  for f in Metal/*.metal; do
    xcrun -sdk $sdk metal -std=metal3.0 -fno-fast-math -c "$f" -o "build/$(basename "$f" .metal)-$sdk.air"
  done
  xcrun -sdk $sdk metallib build/*-$sdk.air -o build/${kit.id}-$sdk.metallib
done
echo "wrote build/${kit.id}-macosx.metallib and build/${kit.id}-iphoneos.metallib"
`;
  files['README.md'] = `# ${kit.name} ${kit.version} — Metal (macOS + iPadOS)

Generated by \`motif-metal\` from the \`motif-kit@1\` kit \`${kit.id}\`. ${kit.styles.length} styles, ${Object.keys(sources).length} Metal passes.

\`\`\`swift
import ${target}
import MotifMetal

let kit = ${kitType}.definition
// SwiftUI (macOS and iPadOS):
MotifView(kit: kit, styleID: "${kit.styles[0].id}", loopSeconds: 6)
\`\`\`

- \`Metal/*.metal\` is the generated source, one file per pass. Edit the web kit and regenerate instead of editing these.
- \`kit.json\` lists styles, parameters (with their buffer slot), palettes and media inputs for non-Swift hosts.
- \`./build-metallib.sh\` optionally precompiles to metallibs.
`;
  return { kit, files, json, warnings, failed, target, kitType };
}

export function writeFiles(dir, files) {
  for (const [rel, text] of Object.entries(files)) {
    const p = path.join(dir, rel); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, text);
    if (rel.endsWith('.sh')) fs.chmodSync(p, 0o755);
  }
}
