#!/usr/bin/env node
// Regenerates every AgentMotif entry point from agent-motif/AGENT.md (the single source of truth):
//   .claude/agents/agent-motif.md              Claude Code subagent (this repo)
//   .claude/skills/agent-motif/SKILL.md        Claude Code skill (/agent-motif)
//   agent-skills/skills/agent-motif/SKILL.md   distributable skill (served by motif-bridge)
//   agent-skills/claude-code/agents/agent-motif.md   distributable subagent
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const body = fs.readFileSync(path.join(repo, 'agent-motif/AGENT.md'), 'utf8');
const description = 'AgentMotif, the shader director for Motif. Use to turn a reference image, a written description, or both into real-time, loopable, art-directable Motif kit entries (styles, effects, transitions, sequences) for SDK 4.0 / motif-kit@4: analyse the reference, decompose it into field/material/light/lens layers with declared field classes, write GLSL on the AgentMotif library, measure against the target, tune parameters, QA loop, flashes, quality-exposure and transition endpoints, pack the kit, and propose SDK features (with pros and cons) when a look needs them.';
const note = '<!-- Generated by agent-motif/tools/sync-agent.mjs from agent-motif/AGENT.md. Edit AGENT.md, then re-run. -->\n\n';
const out = {
  '.claude/agents/agent-motif.md': `---\nname: agent-motif\ndescription: ${description}\ntools: Bash, Read, Write, Edit, Glob, Grep, WebSearch, WebFetch\n---\n\n${note}${body}`,
  '.claude/skills/agent-motif/SKILL.md': `---\nname: agent-motif\ndescription: ${description}\n---\n\n${note}${body}`,
  'agent-skills/skills/agent-motif/SKILL.md': `---\nname: agent-motif\ndescription: ${description}\n---\n\n${note}${body}`,
  'agent-skills/claude-code/agents/agent-motif.md': `---\nname: agent-motif\ndescription: ${description}\ntools: mcp__motif__*, Bash, Read, Write, Edit, Glob, Grep, WebSearch\n---\n\n${note}${body}`,
};
for (const [f, t] of Object.entries(out)) { fs.mkdirSync(path.dirname(path.join(repo, f)), { recursive: true }); fs.writeFileSync(path.join(repo, f), t); console.log('  wrote ' + f); }
