#!/usr/bin/env node
// Regenerates every AgentMotif entry point from agent-motif/AGENT.md (the single source of truth):
//   .claude/agents/agent-motif.md              Claude Code subagent (this repo)
//   .claude/skills/agent-motif/SKILL.md        Claude Code skill (/agent-motif)
//   agent-skills/skills/agent-motif/SKILL.md   distributable skill (served by motif-bridge)
//   agent-skills/claude-code/agents/agent-motif.md   distributable subagent
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const body = fs.readFileSync(path.join(repo, 'agent-motif/AGENT.md'), 'utf8');
const description = 'AgentMotif, the shader director for Motif. Use to turn a reference image, a written description, or both into a real-time, loopable, art-directable shader style (motif-kit@1 / SDK 1.2): analyse the reference, decompose it into light/material/lens layers, write GLSL on the AgentMotif library, measure against the target, tune parameters, QA the loop and flashes, pack the kit, and propose SDK features (with pros and cons) when a look needs them.';
const note = '<!-- Generated by agent-motif/tools/sync-agent.mjs from agent-motif/AGENT.md. Edit AGENT.md, then re-run. -->\n\n';
const out = {
  '.claude/agents/agent-motif.md': `---\nname: agent-motif\ndescription: ${description}\ntools: Bash, Read, Write, Edit, Glob, Grep, WebSearch, WebFetch\n---\n\n${note}${body}`,
  '.claude/skills/agent-motif/SKILL.md': `---\nname: agent-motif\ndescription: ${description}\n---\n\n${note}${body}`,
  'agent-skills/skills/agent-motif/SKILL.md': `---\nname: agent-motif\ndescription: ${description}\n---\n\n${note}${body}`,
  'agent-skills/claude-code/agents/agent-motif.md': `---\nname: agent-motif\ndescription: ${description}\ntools: mcp__motif__*, Bash, Read, Write, Edit, Glob, Grep, WebSearch\n---\n\n${note}${body}`,
};
for (const [f, t] of Object.entries(out)) { fs.mkdirSync(path.dirname(path.join(repo, f)), { recursive: true }); fs.writeFileSync(path.join(repo, f), t); console.log('  wrote ' + f); }
